/*
 * InputIG.java
 *
 * Created on 1 de junio de 2006, 17:05
 */

package graph.input;

import funciones.LimitadorCaracteres;
import funciones.Utilidades;
import graph.beans.IG2Bean;
import java.text.DecimalFormat;
import java.util.ResourceBundle;
import java.util.regex.Pattern;
import javax.swing.CellEditor;
import main.Mensaje;

/**
 *
 * @author  sanjose
 */
public class InputIG2 extends javax.swing.JPanel {
    private static CellEditor cellEditor;
    private static ResourceBundle bundle = ResourceBundle.getBundle("resources/config/config");
    private IG2Bean datosIG2;
    private String mensaje = null;
    
    /** Creates new form InputIG */
    public InputIG2(CellEditor cellEditor) {
        this.cellEditor = cellEditor;
        initComponents();
        establecerRestricciones();
    }
    
    public void installValue(IG2Bean valor) {
        datosIG2 = valor;
        
        if(datosIG2 != null) {
            jTextFieldReferencia.setText(String.valueOf(datosIG2.getReferencia()));
            jComboBoxNumeroPolos.setSelectedItem(DecimalFormat.getInstance().format(datosIG2.getNumeroPolos()));
            jComboBoxCalibre.setSelectedItem(DecimalFormat.getInstance().format(datosIG2.getCalibre()));
            recalcularOpcionesSensibilidad();
            jComboBoxSensibilidad.setSelectedItem(DecimalFormat.getInstance().format(datosIG2.getSensibilidad()));
            jTxtRegulacion.setText(String.valueOf(datosIG2.getRegulacion()));
            jComboBoxPoderDeCorte.setSelectedItem(DecimalFormat.getInstance().format(datosIG2.getPoderDeCorte()));
        } else {
            recalcularOpcionesSensibilidad();
        }
    }
    
    public IG2Bean getValue() {
        return datosIG2;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelRegulacion = new javax.swing.JLabel();
        jTxtRegulacion = new javax.swing.JTextField();
        jLabelRegulacionUnidad = new javax.swing.JLabel();
        jLabelPoderDeCorte = new javax.swing.JLabel();
        jLabelPoderDeCorteUnidad = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jComboBoxPoderDeCorte = new javax.swing.JComboBox();
        jLabelCalibre = new javax.swing.JLabel();
        jLabelSensibilidad = new javax.swing.JLabel();
        jLabelNumeroPolos = new javax.swing.JLabel();
        jComboBoxSensibilidad = new javax.swing.JComboBox();
        jComboBoxCalibre = new javax.swing.JComboBox();
        jComboBoxNumeroPolos = new javax.swing.JComboBox();
        jLabelNumeroPolosUnidad = new javax.swing.JLabel();
        jLabelCalibreUnidad = new javax.swing.JLabel();
        jLabelSensibilidadUnidad = new javax.swing.JLabel();
        jTextFieldReferencia = new javax.swing.JTextField();
        jLabelReferencia = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabelRegulacion.setText("Regulaci\u00f3n");

        jLabelRegulacionUnidad.setText("%");

        jLabelPoderDeCorte.setText("Poder de corte");

        jLabelPoderDeCorteUnidad.setText("KA");

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jComboBoxPoderDeCorte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25", "36", "50", "70", "150" }));

        jLabelCalibre.setText("Calibre");

        jLabelSensibilidad.setText("Sensibilidad");

        jLabelNumeroPolos.setText("N\u00ba Polos");

        jComboBoxCalibre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25", "40", "63", "80", "100" }));
        jComboBoxCalibre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCalibreItemStateChanged(evt);
            }
        });

        jComboBoxNumeroPolos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        jComboBoxNumeroPolos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNumeroPolosItemStateChanged(evt);
            }
        });

        jLabelNumeroPolosUnidad.setText("P");

        jLabelCalibreUnidad.setText("A");

        jLabelSensibilidadUnidad.setText("mA");

        jLabelReferencia.setText("Referencia");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelNumeroPolos)
                            .add(jLabelReferencia))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jComboBoxNumeroPolos, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelNumeroPolosUnidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(38, 38, 38))
                            .add(jTextFieldReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelPoderDeCorte)
                            .add(jLabelRegulacion)
                            .add(jLabelSensibilidad)
                            .add(jLabelCalibre))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jComboBoxSensibilidad, 0, 70, Short.MAX_VALUE)
                            .add(jComboBoxCalibre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtRegulacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .add(jComboBoxPoderDeCorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelCalibreUnidad)
                            .add(jLabelSensibilidadUnidad)
                            .add(jLabelRegulacionUnidad)
                            .add(jLabelPoderDeCorteUnidad))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(140, Short.MAX_VALUE)
                        .add(jBtnAceptar)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jComboBoxCalibre, jComboBoxPoderDeCorte, jComboBoxSensibilidad, jTxtRegulacion}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelReferencia)
                    .add(jTextFieldReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNumeroPolos)
                    .add(jComboBoxNumeroPolos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNumeroPolosUnidad))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCalibre)
                    .add(jLabelCalibreUnidad)
                    .add(jComboBoxCalibre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelSensibilidad)
                    .add(jLabelSensibilidadUnidad)
                    .add(jComboBoxSensibilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelRegulacion)
                    .add(jLabelRegulacionUnidad)
                    .add(jTxtRegulacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelPoderDeCorte)
                    .add(jLabelPoderDeCorteUnidad)
                    .add(jComboBoxPoderDeCorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnAceptar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void jComboBoxNumeroPolosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNumeroPolosItemStateChanged
        recalcularOpcionesSensibilidad();
    }//GEN-LAST:event_jComboBoxNumeroPolosItemStateChanged

    private void jComboBoxCalibreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCalibreItemStateChanged
        recalcularOpcionesSensibilidad();
    }//GEN-LAST:event_jComboBoxCalibreItemStateChanged
    
    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        if(valida()){
            String referencia = (String)jTextFieldReferencia.getText();
            double numeroPolos = 0;
            double calibre = 0;
            double sensibilidad = 0;
            String regulacion = jTxtRegulacion.getText();
            double poderDeCorte = 0;
            try {
                numeroPolos = Double.parseDouble(((String)jComboBoxNumeroPolos.getSelectedItem()).replace(",","."));
                calibre = Double.parseDouble(((String)jComboBoxCalibre.getSelectedItem()).replace(",","."));
                sensibilidad = Double.parseDouble(((String)jComboBoxSensibilidad.getSelectedItem()).replace(",","."));
                poderDeCorte = Double.parseDouble(jComboBoxPoderDeCorte.getSelectedItem().toString().replace(",","."));
            } catch(NumberFormatException e) {}
            datosIG2.setReferencia(referencia);
            datosIG2.setNumeroPolos(numeroPolos);
            datosIG2.setCalibre(calibre);
            datosIG2.setSensibilidad(sensibilidad);
            datosIG2.setRegulacion(regulacion);
            datosIG2.setPoderDeCorte(poderDeCorte);
            datosIG2.setEditado(true);
            cellEditor.stopCellEditing();
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JComboBox jComboBoxCalibre;
    private javax.swing.JComboBox jComboBoxNumeroPolos;
    private javax.swing.JComboBox jComboBoxPoderDeCorte;
    private javax.swing.JComboBox jComboBoxSensibilidad;
    private javax.swing.JLabel jLabelCalibre;
    private javax.swing.JLabel jLabelCalibreUnidad;
    private javax.swing.JLabel jLabelNumeroPolos;
    private javax.swing.JLabel jLabelNumeroPolosUnidad;
    private javax.swing.JLabel jLabelPoderDeCorte;
    private javax.swing.JLabel jLabelPoderDeCorteUnidad;
    private javax.swing.JLabel jLabelReferencia;
    private javax.swing.JLabel jLabelRegulacion;
    private javax.swing.JLabel jLabelRegulacionUnidad;
    private javax.swing.JLabel jLabelSensibilidad;
    private javax.swing.JLabel jLabelSensibilidadUnidad;
    private javax.swing.JTextField jTextFieldReferencia;
    private javax.swing.JTextField jTxtRegulacion;
    // End of variables declaration//GEN-END:variables

    private void establecerRestricciones() {
        jTextFieldReferencia.setDocument(new LimitadorCaracteres(jTextFieldReferencia, 25, false, false));
        jTxtRegulacion.setDocument(new LimitadorCaracteres(jTxtRegulacion, 10, false, false));
    }
        
    private boolean valida(){
        boolean resultado = true;
        this.mensaje=null;
        resultado = resultado && validaReferencia();
        resultado = resultado && validaNumeroPolos();
        resultado = resultado && validaCalibre();
        resultado = resultado && validaSensibilidad();
        resultado = resultado && validaRegulacion();
        resultado = resultado && validaPoderDeCorte();
        if(!resultado){
            // Mostrar mensaje
            Mensaje.error(bundle.getString("ERRORES_EN_DATOS_INTRODUCIDOS")+this.mensaje+"\n");
        }
        return resultado;
    }
    
    private boolean validaReferencia(){
        boolean resultado = true;
        String valor = jTextFieldReferencia.getText();
        String label = jLabelReferencia.getText();
        if(valor==null || "".equals(valor)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO")+" "+label+" "+bundle.getString("ES_OBLIGATORIO")+"\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaNumeroPolos(){
        boolean resultado = true;
        String numeroPolos = (String)jComboBoxNumeroPolos.getSelectedItem();
        if(numeroPolos==null || "".equals(numeroPolos)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelNumeroPolos.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaCalibre(){
        boolean resultado = true;
        String calibre = (String)jComboBoxCalibre.getSelectedItem();
        if(calibre==null || "".equals(calibre)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelCalibre.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaSensibilidad(){
        boolean resultado = true;
        String sensibilidad = (String)jComboBoxSensibilidad.getSelectedItem();
        if(sensibilidad==null || "".equals(sensibilidad)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelSensibilidad.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaRegulacion(){
        boolean resultado = true;
        String regulacion = jTxtRegulacion.getText();
        if(regulacion!=null && !"".equals(regulacion)){
            if(!Pattern.matches("[0-1](,[0-9][0-9]?)??\\s?-\\s?[0-1](,[0-9][0-9]?)??", regulacion)){
                // Mensaje campo con formato incorrecto
                if(mensaje==null)mensaje="";
                mensaje+= bundle.getString("EL_CAMPO");
                mensaje+= " "+jLabelRegulacion.getText()+" ";
                mensaje+= bundle.getString("FORMATO_INCORRECTO");
                mensaje+= "\n";
                resultado=false;
            } else {
                // Comprobar que el primero de los valores es menor que el segundo
                double menor = Double.parseDouble(Utilidades.left(regulacion,"-").trim().replace(",","."));
                double mayor = Double.parseDouble(Utilidades.rightBack(regulacion,"-").trim().replace(",","."));
                if(menor>mayor){
                    // Mensaje campo incorrecto por menor > mayor
                    if(mensaje==null)mensaje="";
                    mensaje+= bundle.getString("EN_EL_CAMPO");
                    mensaje+= " "+jLabelRegulacion.getText()+" ";
                    mensaje+= bundle.getString("EL_PRIMER_VALOR_MENOR");
                    mensaje+= "\n";
                    resultado = false;
                }
            }
        } else {
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelRegulacion.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaPoderDeCorte(){
        boolean resultado = true;
        String poderDeCorte = (String)jComboBoxPoderDeCorte.getSelectedItem();
        if(poderDeCorte==null || "".equals(poderDeCorte)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelPoderDeCorte.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private void recalcularOpcionesSensibilidad(){
        String numeroPolos = (String)jComboBoxNumeroPolos.getSelectedItem();
        String calibre = (String)jComboBoxCalibre.getSelectedItem();
        if("2".equals(numeroPolos) && "25".equals(calibre)){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("10");
            jComboBoxSensibilidad.addItem("30");
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if(("2".equals(numeroPolos) && "40".equals(calibre)) ||
                  ("2".equals(numeroPolos) && "63".equals(calibre)) ||
                  ("2".equals(numeroPolos) && "80".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "25".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "40".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "63".equals(calibre))){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("30");
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if("4".equals(numeroPolos) && "80".equals(calibre)){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if(("2".equals(numeroPolos) && "100".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "100".equals(calibre))){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        }
    }
    
}
