/*
 * InputD1.java
 *
 * Created on 1 de junio de 2006, 17:05
 */

package graph.input;

import funciones.LimitadorCaracteres;
import graph.beans.D1Bean;
import java.text.DecimalFormat;
import java.util.ResourceBundle;
import javax.swing.CellEditor;
import main.Mensaje;

/**
 *
 * @author  sanjose
 */
public class InputD1 extends javax.swing.JPanel {
    private static CellEditor cellEditor;
    private static ResourceBundle bundle = ResourceBundle.getBundle("resources/config/config");
    private D1Bean datosD1;
    private String mensaje = null;
    
    /** Creates new form InputD1 */
    public InputD1(CellEditor cellEditor) {
        this.cellEditor = cellEditor;
        initComponents();
        establecerRestricciones();
    }
    
    public void installValue(D1Bean valor) {
        datosD1 = valor;
        
        if(datosD1 != null) {
            jTextFieldReferencia.setText(String.valueOf(datosD1.getReferencia()));
            jComboBoxNumeroPolos.setSelectedItem(DecimalFormat.getInstance().format(datosD1.getNumeroPolos()));
            jComboBoxCalibre.setSelectedItem(DecimalFormat.getInstance().format(datosD1.getCalibre()));
            recalcularOpcionesSensibilidad();
            jComboBoxSensibilidad.setSelectedItem(DecimalFormat.getInstance().format(datosD1.getSensibilidad()));
        } else {
            recalcularOpcionesSensibilidad();
        }
        
    }
    
    public D1Bean getValue() {
        return datosD1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelSensibilidad = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jLabelSensibilidadUnidad = new javax.swing.JLabel();
        jComboBoxNumeroPolos = new javax.swing.JComboBox();
        jLabelNumeroPolos = new javax.swing.JLabel();
        jLabelCalibre = new javax.swing.JLabel();
        jComboBoxCalibre = new javax.swing.JComboBox();
        jLabelNumeroPolosUnidad = new javax.swing.JLabel();
        jLabelCalibreUnidad = new javax.swing.JLabel();
        jComboBoxSensibilidad = new javax.swing.JComboBox();
        jTextFieldReferencia = new javax.swing.JTextField();
        jLabelReferencia = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabelSensibilidad.setText("Sensibilidad");

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jLabelSensibilidadUnidad.setText("mA");

        jComboBoxNumeroPolos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "4" }));
        jComboBoxNumeroPolos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNumeroPolosItemStateChanged(evt);
            }
        });

        jLabelNumeroPolos.setText("N\u00ba Polos");

        jLabelCalibre.setText("Calibre");

        jComboBoxCalibre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "25", "40", "63", "80", "100" }));
        jComboBoxCalibre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCalibreItemStateChanged(evt);
            }
        });

        jLabelNumeroPolosUnidad.setText("P");

        jLabelCalibreUnidad.setText("A");

        jLabelReferencia.setText("Referencia");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelCalibre)
                            .add(jLabelNumeroPolos)
                            .add(jLabelReferencia)
                            .add(jLabelSensibilidad))
                        .add(4, 4, 4)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldReferencia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBoxNumeroPolos, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBoxCalibre, 0, 62, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBoxSensibilidad, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabelSensibilidadUnidad)
                                    .add(jLabelCalibreUnidad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .add(jLabelNumeroPolosUnidad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnAceptar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelReferencia)
                    .add(jTextFieldReferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxNumeroPolos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNumeroPolosUnidad)
                    .add(jLabelNumeroPolos))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxCalibre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCalibre)
                    .add(jLabelCalibreUnidad))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxSensibilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelSensibilidadUnidad)
                    .add(jLabelSensibilidad))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnAceptar)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void jComboBoxCalibreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCalibreItemStateChanged
        recalcularOpcionesSensibilidad();
    }//GEN-LAST:event_jComboBoxCalibreItemStateChanged

    private void jComboBoxNumeroPolosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNumeroPolosItemStateChanged
        recalcularOpcionesSensibilidad();
    }//GEN-LAST:event_jComboBoxNumeroPolosItemStateChanged
    
    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        if(valida()){
            String referencia = (String)jTextFieldReferencia.getText();
            double numeroPolos = 0;
            double calibre = 0;
            double sensibilidad = 0;
            try {
                numeroPolos = Double.parseDouble(((String)jComboBoxNumeroPolos.getSelectedItem()).replace(",","."));
                calibre = Double.parseDouble(((String)jComboBoxCalibre.getSelectedItem()).replace(",","."));
                sensibilidad = Double.parseDouble(((String)jComboBoxSensibilidad.getSelectedItem()).replace(",","."));
            } catch(NumberFormatException e) {}
            datosD1.setReferencia(referencia);
            datosD1.setNumeroPolos(numeroPolos);
            datosD1.setCalibre(calibre);
            datosD1.setSensibilidad(sensibilidad);
            datosD1.setEditado(true);
            cellEditor.stopCellEditing();
        }
    }//GEN-LAST:event_jBtnAceptarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JComboBox jComboBoxCalibre;
    private javax.swing.JComboBox jComboBoxNumeroPolos;
    private javax.swing.JComboBox jComboBoxSensibilidad;
    private javax.swing.JLabel jLabelCalibre;
    private javax.swing.JLabel jLabelCalibreUnidad;
    private javax.swing.JLabel jLabelNumeroPolos;
    private javax.swing.JLabel jLabelNumeroPolosUnidad;
    private javax.swing.JLabel jLabelReferencia;
    private javax.swing.JLabel jLabelSensibilidad;
    private javax.swing.JLabel jLabelSensibilidadUnidad;
    private javax.swing.JTextField jTextFieldReferencia;
    // End of variables declaration//GEN-END:variables
    
    private void establecerRestricciones() {
        jTextFieldReferencia.setDocument(new LimitadorCaracteres(jTextFieldReferencia, 25, false, false));
    }
        
    private boolean valida(){
        boolean resultado = true;
        this.mensaje=null;
        resultado = resultado && validaReferencia();
        resultado = resultado && validaNumeroPolos();
        resultado = resultado && validaCalibre();
        resultado = resultado && validaSensibilidad();
        if(!resultado){
            // Mostrar mensaje
            Mensaje.error(bundle.getString("ERRORES_EN_DATOS_INTRODUCIDOS")+this.mensaje+"\n");
        }
        return resultado;
    }
    
    private boolean validaReferencia(){
        boolean resultado = true;
        String valor = jTextFieldReferencia.getText();
        String label = jLabelReferencia.getText();
        if(valor==null || "".equals(valor)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO")+" "+label+" "+bundle.getString("ES_OBLIGATORIO")+"\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaNumeroPolos(){
        boolean resultado = true;
        String numeroPolos = (String)jComboBoxNumeroPolos.getSelectedItem();
        if(numeroPolos==null || "".equals(numeroPolos)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelNumeroPolos.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaCalibre(){
        boolean resultado = true;
        String calibre = (String)jComboBoxCalibre.getSelectedItem();
        if(calibre==null || "".equals(calibre)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelCalibre.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private boolean validaSensibilidad(){
        boolean resultado = true;
        String sensibilidad = (String)jComboBoxSensibilidad.getSelectedItem();
        if(sensibilidad==null || "".equals(sensibilidad)){
            // Mensaje campo obligatorio
            if(mensaje==null)mensaje="";
            mensaje+= bundle.getString("EL_CAMPO");
            mensaje+= " "+jLabelSensibilidad.getText()+" ";
            mensaje+= bundle.getString("ES_OBLIGATORIO");
            mensaje+= "\n";
            resultado = false;
        }
        return resultado;
    }
    
    private void recalcularOpcionesSensibilidad(){
        String numeroPolos = (String)jComboBoxNumeroPolos.getSelectedItem();
        String calibre = (String)jComboBoxCalibre.getSelectedItem();
        if("2".equals(numeroPolos) && "25".equals(calibre)){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("10");
            jComboBoxSensibilidad.addItem("30");
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if(("2".equals(numeroPolos) && "40".equals(calibre)) ||
                  ("2".equals(numeroPolos) && "63".equals(calibre)) ||
                  ("2".equals(numeroPolos) && "80".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "25".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "40".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "63".equals(calibre))){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("30");
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if("4".equals(numeroPolos) && "80".equals(calibre)){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.addItem("500");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        } else if(("2".equals(numeroPolos) && "100".equals(calibre)) ||
                  ("4".equals(numeroPolos) && "100".equals(calibre))){
            jComboBoxSensibilidad.removeAllItems();
            jComboBoxSensibilidad.addItem("300");
            jComboBoxSensibilidad.setSelectedIndex(-1);
        }
    }
    
}
