/*
 * DlgAcercaDe.java
 *
 * Created on 29 de mayo de 2006, 17:04
 */

package forms;

import javax.swing.ImageIcon;

/**
 *
 * @author  sanjose
 */
public class DlgAcercaDe extends javax.swing.JDialog {
    
    /** Creates new form DlgAcercaDe */
    public DlgAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextPaneCreditos.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneCreditos = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage((new ImageIcon(getClass().getResource("/resources/icons/sibol.gif"))).getImage());
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/config/config"); // NOI18N
        jLabel2.setText(bundle.getString("TITULO")); // NOI18N

        jLabel3.setText("versión");

        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jLabel4.setText(bundle.getString("VERSION")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/logo_sibol.png"))); // NOI18N

        jTextPaneCreditos.setContentType("text/html");
        jTextPaneCreditos.setEditable(false);
        jTextPaneCreditos.setText("<html>\r\n\n<h1>CRÉDITOS</h1>\n\n<b>Diseño y Coordinación de proyecto:</b><br>\n<ul>\n<li>\nJosé Antonio Bustinza<br>\n<i>Ingeniero Técnico en Electricidad</i>\n</li>\n</ul>\n\n<b>Programación:</b><br>\n<ul>\n<li>\nJavier San José<br>\n<i>Ingeniero Técnico Industrial</i><br>\n<i>Jefe de Proyectos – ODEI, S.A.</i>\n</li>\n</ul>\n\n<b>Diseño Gráfico y Soporte Informático:</b><br>\n<ul>\n<li>\nMª Luisa Muñoz Riaza<br>\n<i>Diseñadora Gráfica – RIAZA ESTUDIO TÉCNICO, S.C.</i>\n</li>\n</ul>\n\n<b>Colaboración Técnica:</b><br>\n<ul>\n<li>\nGustavo Adolfo Martín Rodríguez<br>\n<i>Ingeniero Técnico e Ingeniero Industrial – TALLERES ELÉCTRICOS JOLMA, S.L.</i>\n</li>\n<li>\nAlejandro Nieto Arroyo<br>\n<i>Ingeniero Técnico en Electricidad – ELECTRICIDAD FEMAR, S.L.</i>\n</li>\n</ul>\n\n<b>Empresas Participantes:</b><br>\n<ul>\n<li>ODEI, S.A.</li>\n<li>TALLERES ELÉCTRICOS JOLMA, S.L.</li>\n<li>ELECTRICIDAD DEL VALLE AGUAYO, S.A.</li>\n<li>ELECTRICIDAD FEMAR, S.L.</li>\n<li>ESAN SERVICIOS EMPRESARIALES, S.L.</li>\n<li>MONTAJES ELÉCTRIOS ELCA, S.A.</li>\n<li>MEDELNOR, S.L.</li>\n<li>ELECTROTÉCNICA DE URBINA, S.A.</li>\n</ul>\n\n<b>Agradecimientos:</b><br>\n<ul>\n<li>SEA-EMPRESARIOS ALAVESES</li>\n<li>ASOCIACIÓN DE INSTALADORES ELÉCTRICOS DE ÁLAVA</li>\n<li>FEDERACIÓN DE INSTALADORES DE EUSKADI</li>\n<li>EJIE - SOCIEDAD INFORMÁTICA DEL GOBIERNO VASCO</li>\n</ul>\n\n<b>Mención Especial:</b><br>\nEste proyecto está financiado por mediación de la SPRI.\n\n</html>\r\n");
        jScrollPane1.setViewportView(jTextPaneCreditos);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/spri.gif"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/federacion_instaladores.gif"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/sea.gif"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/instagi.gif"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/aeie.gif"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .addContainerGap()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(6, 6, 6))
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                .add(layout.createSequentialGroup()
                                    .add(jLabel7)
                                    .add(29, 29, 29)
                                    .add(jLabel8)
                                    .add(36, 36, 36))))
                        .add(layout.createSequentialGroup()
                            .add(68, 68, 68)
                            .add(jLabel9)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                    .add(layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel2)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jBtnAceptar)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 474, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(16, 16, 16)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 439, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel5)
                        .add(31, 31, 31)
                        .add(jLabel6)
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(18, 18, 18)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)))
                .add(18, 18, 18)
                .add(jBtnAceptar)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnAceptarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DlgAcercaDe(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneCreditos;
    // End of variables declaration//GEN-END:variables
    
}
