/*
 * DlgCallejeroCaractInst.java
 *
 * Created on 9 de agosto de 2006, 12:11
 */

package forms;

import funciones.AutoComplCmbBxRestrictivo;
import funciones.BaseDatos;
import funciones.LimitadorCaracteres;
import funciones.ParCombo;
import funciones.Sesion;
import funciones.beans.ModeloTablaNoEditable;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import main.Mensaje;

/**
 *
 * @author  enrique
 */
public class DlgCallejeroCaractInst extends javax.swing.JDialog {
    
    BaseDatos bd = null;
    ParCombo pcProv = null;
    ParCombo pcMun = null;
    ParCombo pcLoc = null;
    FrmGestionPnl frmGestion = null;
    
    /** Creates new form DlgCallejeroCaractInst */
    public DlgCallejeroCaractInst(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd = Sesion.getInstance().getBaseDatos();
        frmGestion = (FrmGestionPnl)Sesion.getInstance().getValorHt("objFrmGestionPnl");
        establecerRestricciones();
        agregarDatosCombox();
        pcProv = (ParCombo)Sesion.getInstance().getValorHt("provinciaCaractInst");
        pcMun = (ParCombo)Sesion.getInstance().getValorHt("municipioCaractInst");
        pcLoc = (ParCombo)Sesion.getInstance().getValorHt("localidadCaractInst");
        
        this.jLblProvincia.setText(pcProv.getDescription());
        this.jLblMunicipio.setText(pcMun.getDescription());
        this.jLblLocalidad.setText(pcLoc.getDescription());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblDirecciones = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLblProvincia8 = new javax.swing.JLabel();
        jLblMunicipio8 = new javax.swing.JLabel();
        jLblLocalidad8 = new javax.swing.JLabel();
        jLblProvincia = new javax.swing.JLabel();
        jLblMunicipio = new javax.swing.JLabel();
        jLblLocalidad = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jCmbBxTipoCalle = new javax.swing.JComboBox();
        jTxtFldDireccion = new javax.swing.JTextField();
        jBttnBuscar = new javax.swing.JButton();
        jBttnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("B\u00fasqueda de calles");
        setIconImage((new ImageIcon(getClass().getResource("/resources/icons/sibol.gif"))).getImage());
        setResizable(false);
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTblDirecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de calle", "Dirección"
            }
        ));
        jScrollPane2.setViewportView(jTblDirecciones);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel14.setText("INTRODUZCA B\u00daSQUEDA");

        jLblProvincia8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLblProvincia8.setText("Provincia:");

        jLblMunicipio8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLblMunicipio8.setText("Municipio:");

        jLblLocalidad8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLblLocalidad8.setText("Localidad:");

        jLabel15.setText("Tipo de calle");

        jLabel16.setText("Direcci\u00f3n");

        jCmbBxTipoCalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jBttnBuscar.setText("Buscar");
        jBttnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnBuscarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(jLabel14)
                        .add(190, 190, 190))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLblProvincia8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLblProvincia))
                            .add(jCmbBxTipoCalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel15))
                        .add(7, 7, 7)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jTxtFldDireccion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                                        .add(6, 6, 6)
                                        .add(jBttnBuscar)
                                        .add(0, 0, 0))
                                    .add(jPanel5Layout.createSequentialGroup()
                                        .add(jLabel16)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 435, Short.MAX_VALUE))))
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLblMunicipio8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLblMunicipio)
                                .add(9, 9, 9)
                                .add(jLblLocalidad8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLblLocalidad)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 329, Short.MAX_VALUE)))
                        .add(8, 8, 8))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel14)
                .add(19, 19, 19)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLblProvincia8)
                    .add(jLblLocalidad8)
                    .add(jLblMunicipio8)
                    .add(jLblProvincia)
                    .add(jLblMunicipio)
                    .add(jLblLocalidad))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCmbBxTipoCalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldDireccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jBttnBuscar))))
                .addContainerGap())
        );

        jBttnAceptar.setText("ACEPTAR");
        jBttnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAceptarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBttnAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBttnAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAceptarActionPerformed
        try{
            String tipoCalle = jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(),0).toString();
            String direccion = jTblDirecciones.getValueAt(jTblDirecciones.getSelectedRow(),1).toString();
            frmGestion.jTxtFldEmplazamientoInst.setText(tipoCalle+" - "+direccion);
            this.setVisible(false);
            this.dispose();    
        }
        catch(ArrayIndexOutOfBoundsException e){
            Mensaje.aviso("Seleccione alguna dirección tras haber introducido algún criterio de búsqueda");
        }
    }//GEN-LAST:event_jBttnAceptarActionPerformed

    private void jBttnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnBuscarActionPerformed
        ResultSet rs = null;
        String consulta = "";
        String tipoCalle = this.jCmbBxTipoCalle.getSelectedItem().toString();
        String direccion = this.jTxtFldDireccion.getText();
        
        if(tipoCalle.equals("") && direccion.equals(""))
            consulta = "SELECT * FROM CALLEJERO WHERE CLPRID="+pcProv.getKeyInt()+" AND CLMUID="+pcMun.getKeyInt()+" AND CLLCID="+pcLoc.getKeyInt()+" ORDER BY CLNOM";
        else if(tipoCalle.equals(""))
            consulta = consulta="SELECT * FROM CALLEJERO WHERE CLPRID="+pcProv.getKeyInt()+" AND CLMUID="+pcMun.getKeyInt()+" AND CLLCID="+pcLoc.getKeyInt()+" AND UPPER(CLNOM) LIKE '"+direccion.toUpperCase()+"%'"+" ORDER BY CLNOM";
        else if(direccion.equals(""))
            consulta = consulta="SELECT * FROM CALLEJERO WHERE CLPRID="+pcProv.getKeyInt()+" AND CLMUID="+pcMun.getKeyInt()+" AND CLLCID="+pcLoc.getKeyInt()+" AND CLTIPO = '"+tipoCalle+"'"+" ORDER BY CLNOM";
        else
            consulta = consulta="SELECT * FROM CALLEJERO WHERE CLPRID="+pcProv.getKeyInt()+" AND CLMUID="+pcMun.getKeyInt()+" AND CLLCID="+pcLoc.getKeyInt()+" AND UPPER(CLNOM) LIKE '"+direccion.toUpperCase()+"%' AND CLTIPO='"+tipoCalle+"'"+" ORDER BY CLNOM";
        
        try{
            ModeloTablaNoEditable modelo = null;
            rs = bd.ejecSelect(consulta);
            Object [] col = new Object[2];
            if(rs.next()) {
                modelo = new ModeloTablaNoEditable();
                this.jTblDirecciones.setModel(modelo);
                
                modelo.addColumn("Tipo de calle");
                modelo.addColumn("Dirección");
                rs = bd.ejecSelect(consulta);
                while (rs.next()) {
                    // Se crea un array que será una de las filas de la tabla.
                    // Hay 2 columnas en la tabla
                    
                    col[0] = rs.getObject("CLTIPO");
                    col[1] = rs.getObject("CLNOM");
                    modelo.addRow(col);
                }
                jTblDirecciones.getColumnModel().getColumn(0).setPreferredWidth(100);
                jTblDirecciones.getColumnModel().getColumn(1).setPreferredWidth(350);
            }
            else {
                jTblDirecciones.setModel(new ModeloTablaNoEditable(
                        new Object [][] {},new String [] {
                    "Tipo de calle", "Dirección"
                }
                ));
                jTblDirecciones.getColumnModel().getColumn(0).setPreferredWidth(100);
                jTblDirecciones.getColumnModel().getColumn(1).setPreferredWidth(350);
                Mensaje.aviso("No existe ningún registro con el criterio de búsqueda elegido");
            }            
        } catch(Exception e){
            Mensaje.error("DlgDireccionCaractInst.java: "+e.getMessage(),e);
        }
    }//GEN-LAST:event_jBttnBuscarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DlgCallejeroCaractInst(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    private void establecerRestricciones() {
        jTxtFldDireccion.setDocument(new LimitadorCaracteres(jTxtFldDireccion, 30, false, false));        
    }

    private void agregarDatosCombox() {
        ResultSet rs = null;
        
        try{  
            rs = bd.ejecSelect("SELECT DISTINCT CLTIPO FROM CALLEJERO ORDER BY CLTIPO");
            while(rs.next()){
                this.jCmbBxTipoCalle.addItem(rs.getString("CLTIPO"));
            }
        }
        catch(Exception e){
            Mensaje.error("ERROR EN LA INTERACCIÓN CON LA BD:\n"+e.getMessage());
        }
        
        //Los comboboxes son autocompletables
        new AutoComplCmbBxRestrictivo(this.jCmbBxTipoCalle);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAceptar;
    private javax.swing.JButton jBttnBuscar;
    private javax.swing.JComboBox jCmbBxTipoCalle;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLblLocalidad;
    private javax.swing.JLabel jLblLocalidad8;
    private javax.swing.JLabel jLblMunicipio;
    private javax.swing.JLabel jLblMunicipio8;
    private javax.swing.JLabel jLblProvincia;
    private javax.swing.JLabel jLblProvincia8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblDirecciones;
    private javax.swing.JTextField jTxtFldDireccion;
    // End of variables declaration//GEN-END:variables
    
}
