/*
 * DlgNuevoTecnico.java
 *
 * Created on 9 de agosto de 2006, 13:57
 */

package forms;

import funciones.BaseDatos;
import funciones.LimitadorCaracteres;
import funciones.Sesion;
import funciones.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import main.Constantes;
import main.Mensaje;

/**
 *
 * @author  enrique
 */
public class DlgNuevoTecnico extends javax.swing.JDialog {
    
    private String  nombre, titulo, numero, colegio, nif;
    private FrmGestionPnl frmGestion;
    private BaseDatos bd;
    private boolean esActualizar = false;
    private String txtError;
    
    public DlgNuevoTecnico(javax.swing.JFrame frame, boolean modal) {
        super(frame, modal);
        initComponents();
        establecerRestricciones();
        bd = Sesion.getInstance().getBaseDatos();
        frmGestion = (FrmGestionPnl)Sesion.getInstance().getValorHt("objFrmGestionPnl");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFldNombreTec = new javax.swing.JTextField();
        jTxtFldTituloTec = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jTxtFldColegioOficial = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTxtFldNumColegiado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jTxtFldNIF = new javax.swing.JTextField();
        jBttnAceptar1 = new javax.swing.JButton();
        jBttnCancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo t\u00e9cnico");
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel3.setText("NOMBRE *");

        jLabel18.setText("TITULO *");

        org.jdesktop.layout.GroupLayout jPanel18Layout = new org.jdesktop.layout.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3)
                    .add(jLabel18)
                    .add(jTxtFldNombreTec, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .add(jTxtFldTituloTec))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldNombreTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(jLabel18)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldTituloTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setText("COLEGIO OFICIAL *");

        jLabel20.setText("N\u00ba COLEGIADO *");

        jLabelNIF.setText("DNI *");

        org.jdesktop.layout.GroupLayout jPanel19Layout = new org.jdesktop.layout.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel20)
                    .add(jTxtFldNumColegiado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTxtFldNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNIF))
                .add(31, 31, 31)
                .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jTxtFldColegioOficial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel19Layout.createSequentialGroup()
                        .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel20)
                            .add(jLabelNIF))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldNumColegiado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel19Layout.createSequentialGroup()
                        .add(jLabel19)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel19Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldColegioOficial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBttnAceptar1.setText("ACEPTAR");
        jBttnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAceptar1ActionPerformed(evt);
            }
        });

        jBttnCancelar1.setText("CANCELAR");
        jBttnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnCancelar1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jBttnAceptar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBttnCancelar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jBttnAceptar1, jBttnCancelar1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBttnAceptar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBttnCancelar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnCancelar1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBttnCancelar1ActionPerformed

    private void jBttnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAceptar1ActionPerformed
        if(esValido())
        {
            if(esActualizar)
                this.actualizarBD();
            else
                this.introducirBD();
            
            insertarValoresFrmGestion();
            frmGestion.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        else
            Mensaje.error(txtError);
    }//GEN-LAST:event_jBttnAceptar1ActionPerformed
    
    public boolean esValido()
    {
        txtError = "\n * Error en la introducción de los datos:\n";
        boolean esCorrecto=true;
        if(jTxtFldNombreTec.getText().equals("")){
            esCorrecto=false;
            txtError += "      - NOMBRE no debe de estar vacío.\n";
        }
        if(jTxtFldTituloTec.getText().equals("")){
            esCorrecto=false;
            txtError += "      - TÍTULO TÉCNICO no debe de estar vacío.\n";
        }
        if(jTxtFldNumColegiado.getText().equals("")){
            esCorrecto=false;
            txtError += "      - Nº COLEGIADO no debe de estar vacío.\n";
        }
        if(jTxtFldNIF.getText().equals("")){
            esCorrecto=false;
            txtError += "      - DNI no debe de estar vacío.\n";
        }
        if(!Utilidades.esDniNifValido(jTxtFldNIF.getText()))
        {
            esCorrecto=false;
            txtError += "      - DNI no contiene un valor válido.\n";
        }
        if(jTxtFldColegioOficial.getText().equals("")){
            esCorrecto=false;
            txtError += "      - COLEGIO OFICIAL no debe de estar vacío.\n";
        }
        
        return esCorrecto;
          
    }
    
    private void introducirBD() {
        ResultSet rs = null;
        nombre = jTxtFldNombreTec.getText();
        titulo = jTxtFldTituloTec.getText();
        numero = jTxtFldColegioOficial.getText();
        nif = jTxtFldNIF.getText();
        colegio = jTxtFldNumColegiado.getText();
        
        BaseDatos bd = Sesion.getInstance().getBaseDatos();
        String consulta ="INSERT INTO TECNICOS_CUALIFICADOS (TCNOMBRE, TCTITULO, TCNUMCOLEGIADO, TCNIF, TCCOLEGIO)" +
                " VALUES('"+nombre+"','"+titulo+"','"+numero+"','"+nif+"','"+colegio+"')";
        
        try {
            bd.ejecModificacion(consulta);
            consulta = "SELECT * FROM TECNICOS_CUALIFICADOS";
            rs = bd.getUltimoResgistro(consulta);
            
            //Guardar en la sesión la ID de SES_TECNICOS_CUALIFICADOS_ID
            Sesion.getInstance().setValorHt(Constantes.SES_TECNICOS_CUALIFICADOS_ID, rs.getString(Constantes.SES_TECNICOS_CUALIFICADOS_ID));   
        } 
        catch (SQLException e) {
            Mensaje.error("DlgNuevoTecnico.java. "+e.getMessage(),e);
        } 
    }

    private void insertarValoresFrmGestion() {
        frmGestion.jTxtFldNombreTec.setText(nombre);
        frmGestion.jTxtFldTituloTec.setText(titulo);
        frmGestion.jTxtFldNumColegiado.setText(numero);
        frmGestion.jTxtFldNIF.setText(nif);
        frmGestion.jTxtFldColegioOficial.setText(colegio);
    }

    public void establecerRestricciones()
    {
        jTxtFldNombreTec.setDocument(new LimitadorCaracteres(jTxtFldNombreTec, 40,false, false));
        jTxtFldTituloTec.setDocument(new LimitadorCaracteres(jTxtFldTituloTec, 50,false, false));
        jTxtFldNumColegiado.setDocument(new LimitadorCaracteres(jTxtFldNumColegiado, 10,false, false));
        jTxtFldNIF.setDocument(new LimitadorCaracteres(jTxtFldNIF, 9,false, false));
        jTxtFldColegioOficial.setDocument(new LimitadorCaracteres(jTxtFldColegioOficial, 50,false, false));
    }
    
    public void setEsActualizar(boolean esActualizar){
        this.esActualizar = esActualizar;
    }

    private void actualizarBD() {
        ResultSet rs = null;
        nombre  = jTxtFldNombreTec.getText();
        titulo  = jTxtFldTituloTec.getText(); 
        numero  = jTxtFldNumColegiado.getText();
        nif  = jTxtFldNIF.getText();
        colegio = jTxtFldColegioOficial.getText();
       
       
        BaseDatos bd = Sesion.getInstance().getBaseDatos();
        String consulta ="UPDATE TECNICOS_CUALIFICADOS SET TCNOMBRE='"+nombre+"', " +
                " TCTITULO='"+titulo+"', TCNUMCOLEGIADO='"+numero+"', TCNIF='"+nif+"', TCCOLEGIO='"+colegio+"' " +
                " WHERE TCID="+Sesion.getInstance().getValorHt(Constantes.SES_TECNICOS_CUALIFICADOS_ID).toString();
        
        try {
            bd.ejecModificacion(consulta);   
        } 
        catch (SQLException e) {
            Mensaje.error("DlgNuevoTecnico.java. "+e.getMessage(),e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAceptar1;
    private javax.swing.JButton jBttnCancelar1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    public javax.swing.JTextField jTxtFldColegioOficial;
    public javax.swing.JTextField jTxtFldNIF;
    public javax.swing.JTextField jTxtFldNombreTec;
    public javax.swing.JTextField jTxtFldNumColegiado;
    public javax.swing.JTextField jTxtFldTituloTec;
    // End of variables declaration//GEN-END:variables
    
}
