/*
 * DlgSeleccionarTecnico.java
 *
 * Created on 9 de agosto de 2006, 12:54
 */

package forms;

import funciones.BaseDatos;
import funciones.ParCombo;
import funciones.Sesion;
import funciones.beans.ModeloTablaNoEditable;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import main.Constantes;
import main.Mensaje;

public class DlgSeleccionarTecnico extends javax.swing.JDialog {
    
    BaseDatos bd = null;
    ParCombo pcFilaSeleccionada = null;
    FrmGestionPnl frmGestion = null;
    FrmPrincipal frmPrincipal = null;
    DlgNuevoTecnico dlgNuevoTecnico = null;
    
    public DlgSeleccionarTecnico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd = Sesion.getInstance().getBaseDatos();
        frmGestion = (FrmGestionPnl)Sesion.getInstance().getValorHt("objFrmGestionPnl");
        frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtFldNombreTecnico = new javax.swing.JTextField();
        jBttnNuevo = new javax.swing.JButton();
        jBttnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbTecnico = new javax.swing.JTable();
        jBttnAceptar = new javax.swing.JButton();
        jBttnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("B\u00fasqueda de t\u00e9cnicos");
        setIconImage((new ImageIcon(getClass().getResource("/resources/icons/sibol.gif"))).getImage());
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setText("NOMBRE T\u00c9CNICO");

        jBttnNuevo.setText("DAR DE ALTA NUEVO");
        jBttnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnNuevoActionPerformed(evt);
            }
        });

        jBttnBuscar.setText("BUSCAR");
        jBttnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INTRODUZCA B\u00daSQUEDA");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jBttnNuevo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBttnBuscar))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldNombreTecnico, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {jBttnBuscar, jBttnNuevo}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .add(25, 25, 25)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTxtFldNombreTecnico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBttnBuscar)
                    .add(jBttnNuevo))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTbTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre técnico", "Título", "Nº Colegiado", "DNI", "Colegio oficial"
            }
        ));
        jTbTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbTecnicoMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(jTbTecnico);

        jBttnAceptar.setText("ACEPTAR");
        jBttnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAceptarActionPerformed(evt);
            }
        });

        jBttnModificar.setText("MODIFICAR");
        jBttnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnModificarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jBttnAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBttnModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jBttnAceptar, jBttnModificar}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBttnModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jBttnAceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbTecnicoMouseClicked
        // doble click sobre la tabla
        if(evt.getClickCount() == 2) {
            jBttnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_jTbTecnicoMouseClicked

    private void jBttnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnModificarActionPerformed
        try{
            dlgNuevoTecnico = new DlgNuevoTecnico(frmPrincipal, true);
            dlgNuevoTecnico.setEsActualizar(true);
            pcFilaSeleccionada = (ParCombo)jTbTecnico.getValueAt(jTbTecnico.getSelectedRow(),0);
            insertarValoresDlgNuevoTecnico();
            this.setVisible(false);
            dlgNuevoTecnico.setVisible(true);
        }
        catch(ArrayIndexOutOfBoundsException e){
           Mensaje.aviso("Seleccione algún nombre tras haber introducido algún criterio de búsqueda");
       }
    }//GEN-LAST:event_jBttnModificarActionPerformed

    private void jBttnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAceptarActionPerformed
        try{
            pcFilaSeleccionada = (ParCombo)jTbTecnico.getValueAt(jTbTecnico.getSelectedRow(),0);
            insertarValoresFrmGestion();
            this.setVisible(false);
            this.dispose();
        } catch(ArrayIndexOutOfBoundsException e){
            Mensaje.aviso("Seleccione algún nombre tras haber introducido algún criterio de búsqueda");
        }
    }//GEN-LAST:event_jBttnAceptarActionPerformed

    private void jBttnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnBuscarActionPerformed
        ResultSet rs = null;
        String consulta = "";
        String nombreTecnico = this.jTxtFldNombreTecnico.getText();
        
        if(nombreTecnico.equals(""))
            consulta = "SELECT * FROM TECNICOS_CUALIFICADOS";
        else
            consulta = consulta="SELECT * FROM TECNICOS_CUALIFICADOS WHERE UPPER(TCNOMBRE) LIKE '"+nombreTecnico.toUpperCase()+"%'";
        
        try{
            ModeloTablaNoEditable modelo = null;
            rs = bd.ejecSelect(consulta);
            Object [] col = new Object[8];
            if(rs.next()) {
                modelo = new ModeloTablaNoEditable();
                this.jTbTecnico.setModel(modelo);
                
                modelo.addColumn("Nombre técnico");
                modelo.addColumn("Título");
                modelo.addColumn("Nº Colegiado");
                modelo.addColumn("DNI");
                modelo.addColumn("Colegio oficial");
                
                rs = bd.ejecSelect(consulta);
                while (rs.next()) {
                    col[0] = new ParCombo(rs.getString(Constantes.SES_TECNICOS_CUALIFICADOS_ID),rs.getString("TCNOMBRE"));
                    col[1] = rs.getString("TCTITULO");
                    col[2] = rs.getString("TCNUMCOLEGIADO");
                    col[3] = rs.getString("TCNIF");
                    col[4] = rs.getString("TCCOLEGIO");
                    modelo.addRow(col);
                }
            } else {
                jTbTecnico.setModel(new ModeloTablaNoEditable(
                        new Object [][] {},new String [] {"Nombre técnico", "Título", "Nº Colegiado", "DNI", "Colegio oficial"}));
                Mensaje.aviso("No existe ningún registro con el criterio de búsqueda elegido");
            }
        } catch(Exception e){
            Mensaje.error("DlgSeleccionarTecnico.java: "+e.getMessage(),e);
        }
    }//GEN-LAST:event_jBttnBuscarActionPerformed

    private void jBttnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnNuevoActionPerformed
        FrmPrincipal frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
        DlgNuevoTecnico dlgNuevo = new DlgNuevoTecnico(frmPrincipal, true);
        dlgNuevo.setLocationRelativeTo(frmPrincipal);
        this.setVisible(false);
        dlgNuevo.setVisible(true);
    }//GEN-LAST:event_jBttnNuevoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DlgSeleccionarTecnico(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    private void insertarValoresFrmGestion() {
        ResultSet rs = null;
        String consulta = "SELECT * FROM TECNICOS_CUALIFICADOS WHERE TCID="+pcFilaSeleccionada.getKeyString();
        
        try{
            rs = bd.ejecSelect(consulta);
            rs.next();
            //Guardar en la sesión la ID de TECNICOS_CUALIFICADOS
            Sesion.getInstance().setValorHt(Constantes.SES_TECNICOS_CUALIFICADOS_ID, rs.getString(Constantes.SES_TECNICOS_CUALIFICADOS_ID));
            frmGestion.jTxtFldNombreTec.setText(rs.getString("TCNOMBRE"));
            frmGestion.jTxtFldTituloTec.setText(rs.getString("TCTITULO"));
            frmGestion.jTxtFldNumColegiado.setText(rs.getString("TCNUMCOLEGIADO"));
            frmGestion.jTxtFldColegioOficial.setText(rs.getString("TCCOLEGIO"));
            frmGestion.jTxtFldNIF.setText(rs.getString("TCNIF"));
        }
        catch(SQLException e){
            Mensaje.error("DlgSeleccionarTecnico.java. "+e.getMessage(),e);
        }
    }

    private void insertarValoresDlgNuevoTecnico() {
        ResultSet rs = null;
        String consulta = "SELECT * FROM TECNICOS_CUALIFICADOS WHERE TCID="+pcFilaSeleccionada.getKeyString();
        
        try{
            rs = bd.ejecSelect(consulta);
            rs.next();
            //Guardar en la sesión la ID de TECNICOS_CUALIFICADOS
            Sesion.getInstance().setValorHt(Constantes.SES_TECNICOS_CUALIFICADOS_ID, rs.getString(Constantes.SES_TECNICOS_CUALIFICADOS_ID));
            dlgNuevoTecnico.jTxtFldNombreTec.setText(rs.getString("TCNOMBRE"));
            dlgNuevoTecnico.jTxtFldTituloTec.setText(rs.getString("TCTITULO"));
            dlgNuevoTecnico.jTxtFldNumColegiado.setText(rs.getString("TCNUMCOLEGIADO"));
            dlgNuevoTecnico.jTxtFldColegioOficial.setText(rs.getString("TCCOLEGIO"));
            dlgNuevoTecnico.jTxtFldNIF.setText(rs.getString("TCNIF"));
        }
        catch(SQLException e){
            Mensaje.error("DlgSeleccionarTecnico.java. "+e.getMessage(),e);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAceptar;
    private javax.swing.JButton jBttnBuscar;
    private javax.swing.JButton jBttnModificar;
    private javax.swing.JButton jBttnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbTecnico;
    private javax.swing.JTextField jTxtFldNombreTecnico;
    // End of variables declaration//GEN-END:variables
    
}
