/*
 * FrmGestionPnl.java
 *
 * Created on 26 de julio de 2006, 14:44
 */

package forms;

import funciones.AutoComplCmbBxRestrictivo;
import funciones.BaseDatos;
import funciones.LimitadorCaracteres;
import funciones.ParCombo;
import funciones.Sesion;
import funciones.Utilidades;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.UIManager;
import main.Constantes;
import main.Mensaje;

/**
 *
 * @author  enrique
 */
public class FrmGestionPnl extends javax.swing.JPanel {
    
    BaseDatos bd = null;
    DefaultComboBoxModel modLoc, modProv, modMun;
    private int codProv, codMun, codCiudad;
    private String nomProv, nomMun, nomCiudad;
    
    /**
     * Creates new form FrmGestionPnl
     */
    public FrmGestionPnl() {
        //Guardo esta clase en la sesion
        Sesion.getInstance().setValorHt("objFrmGestionPnl",this);
        bd = Sesion.getInstance().getBaseDatos();
        initComponents();
        UIManager.put("ComboBox.disabledBackground", new Color(Constantes.GRIS_COMBOS,Constantes.GRIS_COMBOS,Constantes.GRIS_COMBOS));
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);
        establecerRestricciones();
        agregarDatosCombox();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTbbdPnGestion = new javax.swing.JTabbedPane();
        jPnlTitular = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFldNombreTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtFldNifTitular = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTxtFldCpTitular = new javax.swing.JTextField();
        jCmbBxLocalidadTitular = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jCmbBxMunicipioTitular = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCmbBxProvinciaTitular = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTxtFldDomicilioTitular = new javax.swing.JTextField();
        jBtnDirTitular = new javax.swing.JButton();
        jTxtFldTelefonoTitular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtFldPortalTit = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTxtFldBisTit = new javax.swing.JTextField();
        jTxtFldEscaleraTit = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTxtFldPisoTit = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTxtFldPuertaTit = new javax.swing.JTextField();
        jLabelEmailInstalacion = new javax.swing.JLabel();
        jTxtFldEmailInstalacion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtFldRepresentanteTitular = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtFldNifRepr = new javax.swing.JTextField();
        jPnlEmpSum = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTxtFldCups1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTxtFldCups3 = new javax.swing.JTextField();
        jTxtFldCups2 = new javax.swing.JTextField();
        jCmbBxEmpSuministradora = new javax.swing.JComboBox();
        jPnlEmpInst = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jBttnSelecInstalador = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtFldNombreEmpresa = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTxtFldNumEmpresa = new javax.swing.JTextField();
        jTxtFldEibt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTxtFldNombreInst = new javax.swing.JTextField();
        jTxtFldNumCarne = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTxtFldCcbt = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTxtFldNIFInstalador = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTxtFldEmailEmp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTxtFldTelefonoEmp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jCmbBxModalidadEmp = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jCmbBxCatInst = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jPnlCaractInst = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jBtnDirCaractInst = new javax.swing.JButton();
        jTxtFldEmplazamientoInst = new javax.swing.JTextField();
        jTxtFldPortalInst = new javax.swing.JTextField();
        jTxtFldBisInst = new javax.swing.JTextField();
        jTxtFldEscaleraInst = new javax.swing.JTextField();
        jTxtFldPisoInst = new javax.swing.JTextField();
        jTxtFldPuertaInst = new javax.swing.JTextField();
        jTxtFldTelefonoInstalacion = new javax.swing.JTextField();
        jLabelTelefonoInstalacion = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jCmbBxProvinciaInst = new javax.swing.JComboBox();
        jCmbBxMunicipioInst = new javax.swing.JComboBox();
        jCmbBxLocalidadInst = new javax.swing.JComboBox();
        jTxtFldCpInst = new javax.swing.JTextField();
        jPnlTecnicoCualif = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtFldNombreTec = new javax.swing.JTextField();
        jTxtFldTituloTec = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jTxtFldColegioOficial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtFldNumColegiado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabelNIF = new javax.swing.JLabel();
        jTxtFldNIF = new javax.swing.JTextField();
        jBttnSelecTecnico = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setAutoscrolls(true);
        jLabel3.setText("APELLIDOS Y NOMBRE O RAZON SOCIAL *");

        jTxtFldNombreTitular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtFldNombreTitular.setAutoscrolls(false);

        jLabel4.setText("NIF / CIF *");

        jTxtFldNifTitular.setAutoscrolls(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jTxtFldNombreTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 465, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jTxtFldNifTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTxtFldNifTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtFldNombreTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("C. P. *");

        jCmbBxLocalidadTitular.setEditable(true);

        jLabel10.setText("LOCALIDAD *");

        jCmbBxMunicipioTitular.setEditable(true);
        jCmbBxMunicipioTitular.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxMunicipioTitularItemStateChanged(evt);
            }
        });

        jLabel7.setText("MUNICIPIO *");

        jCmbBxProvinciaTitular.setEditable(true);
        jCmbBxProvinciaTitular.setName("jCmbBxTerritorioHistTitular");
        jCmbBxProvinciaTitular.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxProvinciaTitularItemStateChanged(evt);
            }
        });

        jLabel8.setText("PROVINCIA *");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCmbBxProvinciaTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jCmbBxMunicipioTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(14, 14, 14)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCmbBxLocalidadTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10)))
                    .add(jLabel9)
                    .add(jTxtFldCpTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jPanel3Layout.createSequentialGroup()
                            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jLabel7)
                                .add(jLabel10))
                            .add(28, 28, 28))
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jCmbBxMunicipioTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCmbBxProvinciaTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCmbBxLocalidadTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(16, 16, 16)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldCpTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(new java.awt.Component[] {jCmbBxLocalidadTitular, jCmbBxMunicipioTitular, jCmbBxProvinciaTitular}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jLabel5.setText("DOMICILIO (calle plaza o n\u00famero) *");

        jTxtFldDomicilioTitular.setAutoscrolls(false);

        jBtnDirTitular.setText("...");
        jBtnDirTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDirTitularActionPerformed(evt);
            }
        });

        jTxtFldTelefonoTitular.setAutoscrolls(false);

        jLabel6.setText("TELEFONO *");

        jLabel45.setText("Portal");

        jLabel46.setText("Bis");

        jLabel47.setText("Escalera");

        jLabel48.setText("Piso");

        jLabel49.setText("Puerta");

        jLabelEmailInstalacion.setText("E-MAIL");

        jTxtFldEmailInstalacion.setAutoscrolls(false);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 567, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTxtFldDomicilioTitular, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnDirTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel45)
                            .add(jTxtFldPortalTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel46)
                            .add(jTxtFldBisTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(14, 14, 14)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel47)
                            .add(jTxtFldEscaleraTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel48)
                            .add(jTxtFldPisoTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtFldPuertaTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel49))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 275, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jTxtFldTelefonoTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(62, 62, 62))
                    .add(jLabelEmailInstalacion)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jTxtFldEmailInstalacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 327, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(474, Short.MAX_VALUE))))
        );

        jPanel4Layout.linkSize(new java.awt.Component[] {jTxtFldBisTit, jTxtFldEscaleraTit, jTxtFldPisoTit, jTxtFldPortalTit, jTxtFldPuertaTit}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnDirTitular)
                    .add(jTxtFldDomicilioTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel45)
                            .add(jLabel46)
                            .add(jLabel47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel48)
                            .add(jLabel49)
                            .add(jLabel6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldBisTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldEscaleraTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldPisoTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldPuertaTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldTelefonoTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jTxtFldPortalTit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(16, 16, 16)
                .add(jLabelEmailInstalacion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldEmailInstalacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("REPRESENTANTE (si procede)");

        jTxtFldRepresentanteTitular.setAutoscrolls(false);

        jLabel12.setText("NIF Representante");

        jTxtFldNifRepr.setAutoscrolls(false);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11)
                    .add(jTxtFldRepresentanteTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 556, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel12)
                    .add(jTxtFldNifRepr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldNifRepr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldRepresentanteTitular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPnlTitularLayout = new org.jdesktop.layout.GroupLayout(jPnlTitular);
        jPnlTitular.setLayout(jPnlTitularLayout);
        jPnlTitularLayout.setHorizontalGroup(
            jPnlTitularLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlTitularLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlTitularLayout.setVerticalGroup(
            jPnlTitularLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlTitularLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTbbdPnGestion.addTab("Titular", jPnlTitular);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel21.setText("NOMBRE EMPRESA SUMINISTRADORA *");

        jLabel43.setText("/");

        jTxtFldCups1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFldCups1FocusLost(evt);
            }
        });

        jLabel38.setText("CUPS");

        jLabel41.setText("/");

        jTxtFldCups3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFldCups3FocusLost(evt);
            }
        });

        jTxtFldCups2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFldCups2FocusLost(evt);
            }
        });

        jCmbBxEmpSuministradora.setEditable(true);

        org.jdesktop.layout.GroupLayout jPanel18Layout = new org.jdesktop.layout.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jCmbBxEmpSuministradora, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel21)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel38)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel18Layout.createSequentialGroup()
                        .add(jTxtFldCups1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel41)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldCups2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel43)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldCups3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCmbBxEmpSuministradora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19)
                .add(jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel18Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel18Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldCups1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldCups2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldCups3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPnlEmpSumLayout = new org.jdesktop.layout.GroupLayout(jPnlEmpSum);
        jPnlEmpSum.setLayout(jPnlEmpSumLayout);
        jPnlEmpSumLayout.setHorizontalGroup(
            jPnlEmpSumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlEmpSumLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlEmpSumLayout.setVerticalGroup(
            jPnlEmpSumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlEmpSumLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTbbdPnGestion.addTab("Empresa suministradora", jPnlEmpSum);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jBttnSelecInstalador.setText("Seleccionar instalador");
        jBttnSelecInstalador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSelecInstaladorActionPerformed(evt);
            }
        });

        jLabel1.setText("APELLIDOS Y NOMBRE O RAZON SOCIAL");

        jTxtFldNombreEmpresa.setEditable(false);
        jTxtFldNombreEmpresa.setAutoscrolls(false);

        jLabel23.setText("N\u00ba de EMPRESA");

        jTxtFldNumEmpresa.setEditable(false);
        jTxtFldNumEmpresa.setAutoscrolls(false);

        jTxtFldEibt.setEditable(false);
        jTxtFldEibt.setAutoscrolls(false);

        jLabel39.setText("/ EIBT -");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jTxtFldNombreEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 388, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel23)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jTxtFldNumEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel39)
                        .add(4, 4, 4)
                        .add(jTxtFldEibt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldNombreEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldNumEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel39)
                            .add(jTxtFldEibt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel23))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("NOMBRE DEL INSTALADOR");

        jTxtFldNombreInst.setEditable(false);
        jTxtFldNombreInst.setAutoscrolls(false);

        jTxtFldNumCarne.setEditable(false);
        jTxtFldNumCarne.setAutoscrolls(false);

        jLabel25.setText("N\u00ba del CARN\u00c9");

        jTxtFldCcbt.setEditable(false);
        jTxtFldCcbt.setAutoscrolls(false);

        jLabel40.setText("/ CCBT -");

        jTxtFldNIFInstalador.setEditable(false);
        jTxtFldNIFInstalador.setAutoscrolls(false);

        jLabel42.setText("DNI");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel24)
                    .add(jTxtFldNombreInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 387, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel25)
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jTxtFldNumCarne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel40)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldCcbt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(41, 41, 41)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTxtFldNIFInstalador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel42))
                .add(80, 80, 80))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel25)
                        .add(jLabel42))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldNombreInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldNIFInstalador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldNumCarne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel40)
                            .add(jTxtFldCcbt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTxtFldEmailEmp.setEditable(false);
        jTxtFldEmailEmp.setAutoscrolls(false);

        jLabel29.setText("E-MAIL");

        jTxtFldTelefonoEmp.setEditable(false);
        jTxtFldTelefonoEmp.setAutoscrolls(false);

        jLabel28.setText("TELEFONO");

        jCmbBxModalidadEmp.setEditable(true);
        jCmbBxModalidadEmp.setEnabled(false);

        jLabel27.setText("MODALIDAD");

        jCmbBxCatInst.setEditable(true);
        jCmbBxCatInst.setEnabled(false);

        jLabel26.setText("CATEGOR\u00cdA INSTALADOR");

        org.jdesktop.layout.GroupLayout jPanel10Layout = new org.jdesktop.layout.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel26)
                            .add(jCmbBxCatInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16)
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCmbBxModalidadEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel27))
                        .add(24, 24, 24)
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtFldTelefonoEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel28))
                        .addContainerGap(369, Short.MAX_VALUE))
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel29)
                            .add(jTxtFldEmailEmp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                        .add(564, 564, 564))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel26)
                            .add(jLabel27))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jCmbBxModalidadEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jTxtFldTelefonoEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jCmbBxCatInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel28))
                .add(17, 17, 17)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel10Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jTxtFldEmailEmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel29))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBttnSelecInstalador))
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 800, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(23, 23, 23))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jBttnSelecInstalador)
                        .add(33, 33, 33)))
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23)
                .add(jPanel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPnlEmpInstLayout = new org.jdesktop.layout.GroupLayout(jPnlEmpInst);
        jPnlEmpInst.setLayout(jPnlEmpInstLayout);
        jPnlEmpInstLayout.setHorizontalGroup(
            jPnlEmpInstLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlEmpInstLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlEmpInstLayout.setVerticalGroup(
            jPnlEmpInstLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPnlEmpInstLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTbbdPnGestion.addTab("Empresa / Instalador", jPnlEmpInst);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel20.setText("EMPLAZAMIENTO *");

        jLabel22.setText("Portal");

        jLabel30.setText("Bis");

        jLabel31.setText("Escalera");

        jLabel32.setText("Piso");

        jLabel34.setText("Puerta");

        jBtnDirCaractInst.setText("...");
        jBtnDirCaractInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDirCaractInstActionPerformed(evt);
            }
        });

        jTxtFldTelefonoInstalacion.setAutoscrolls(false);

        jLabelTelefonoInstalacion.setText("TELEFONO *");

        org.jdesktop.layout.GroupLayout jPanel11Layout = new org.jdesktop.layout.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel20)
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(jTxtFldEmplazamientoInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 477, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBtnDirCaractInst))
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel22)
                            .add(jTxtFldPortalInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(15, 15, 15)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel30)
                            .add(jTxtFldBisInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(14, 14, 14)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel31)
                            .add(jTxtFldEscaleraInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(20, 20, 20)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel32)
                            .add(jTxtFldPisoInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(19, 19, 19)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtFldPuertaInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel34))
                        .add(88, 88, 88)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtFldTelefonoInstalacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelTelefonoInstalacion))))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(new java.awt.Component[] {jTxtFldBisInst, jTxtFldEscaleraInst, jTxtFldPisoInst, jTxtFldPortalInst, jTxtFldPuertaInst}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel20)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jBtnDirCaractInst)
                    .add(jTxtFldEmplazamientoInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel30)
                                    .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel32)))
                                .add(jLabel22))
                            .add(jLabel34))
                        .add(26, 26, 26))
                    .add(jPanel11Layout.createSequentialGroup()
                        .add(jLabelTelefonoInstalacion)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldBisInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldEscaleraInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldPisoInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldPuertaInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldPortalInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldTelefonoInstalacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel37.setText("PROVINCIA *");

        jLabel35.setText("MUNICIPIO *");

        jLabel33.setText("LOCALIDAD *");

        jLabel36.setText("C. P. *");

        jCmbBxProvinciaInst.setEditable(true);
        jCmbBxProvinciaInst.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxProvinciaInstItemStateChanged(evt);
            }
        });

        jCmbBxMunicipioInst.setEditable(true);
        jCmbBxMunicipioInst.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbBxMunicipioInstItemStateChanged(evt);
            }
        });

        jCmbBxLocalidadInst.setEditable(true);

        org.jdesktop.layout.GroupLayout jPanel13Layout = new org.jdesktop.layout.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel13Layout.createSequentialGroup()
                        .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel37)
                            .add(jCmbBxProvinciaInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(15, 15, 15)
                        .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel35)
                            .add(jCmbBxMunicipioInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(17, 17, 17)
                        .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCmbBxLocalidadInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel33)))
                    .add(jLabel36)
                    .add(jTxtFldCpInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel13Layout.createSequentialGroup()
                        .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel37)
                            .add(jLabel35))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jCmbBxProvinciaInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCmbBxMunicipioInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel13Layout.createSequentialGroup()
                        .add(jLabel33)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCmbBxLocalidadInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(14, 14, 14)
                .add(jLabel36)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldCpInst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel12Layout = new org.jdesktop.layout.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPnlCaractInstLayout = new org.jdesktop.layout.GroupLayout(jPnlCaractInst);
        jPnlCaractInst.setLayout(jPnlCaractInstLayout);
        jPnlCaractInstLayout.setHorizontalGroup(
            jPnlCaractInstLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlCaractInstLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlCaractInstLayout.setVerticalGroup(
            jPnlCaractInstLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlCaractInstLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTbbdPnGestion.addTab("<html>Caracter\u00edsticas<br>de la instalaci\u00f3n</html>", jPnlCaractInst);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel2.setText("NOMBRE");

        jTxtFldNombreTec.setEditable(false);

        jTxtFldTituloTec.setEditable(false);

        jLabel13.setText("TITULO");

        org.jdesktop.layout.GroupLayout jPanel15Layout = new org.jdesktop.layout.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel13)
                    .add(jTxtFldTituloTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtFldNombreTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 467, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldNombreTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFldTituloTec, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTxtFldColegioOficial.setEditable(false);

        jLabel15.setText("COLEGIO OFICIAL");

        jTxtFldNumColegiado.setEditable(false);

        jLabel14.setText("N\u00ba COLEGIADO");

        jLabelNIF.setText("DNI");

        jTxtFldNIF.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel16Layout = new org.jdesktop.layout.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(jTxtFldNumColegiado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNIF)
                    .add(jTxtFldNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel15)
                    .add(jTxtFldColegioOficial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel16Layout.createSequentialGroup()
                        .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel14)
                            .add(jLabelNIF))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtFldNumColegiado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtFldNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel16Layout.createSequentialGroup()
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFldColegioOficial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBttnSelecTecnico.setText("Seleccionar t\u00e9cnico");
        jBttnSelecTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSelecTecnicoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel17Layout = new org.jdesktop.layout.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel17Layout.createSequentialGroup()
                        .add(jPanel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jBttnSelecTecnico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(341, 341, 341))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel17Layout.createSequentialGroup()
                .add(jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel17Layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jBttnSelecTecnico)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPnlTecnicoCualifLayout = new org.jdesktop.layout.GroupLayout(jPnlTecnicoCualif);
        jPnlTecnicoCualif.setLayout(jPnlTecnicoCualifLayout);
        jPnlTecnicoCualifLayout.setHorizontalGroup(
            jPnlTecnicoCualifLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlTecnicoCualifLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1071, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnlTecnicoCualifLayout.setVerticalGroup(
            jPnlTecnicoCualifLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlTecnicoCualifLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTbbdPnGestion.addTab("T\u00e9cnico cualificado", jPnlTecnicoCualif);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTbbdPnGestion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTbbdPnGestion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFldCups3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFldCups3FocusLost
        if(!"".equals(jTxtFldCups3.getText())) jTxtFldCups3.setText(Utilidades.rellenarCeros(jTxtFldCups3.getText(), 2));
    }//GEN-LAST:event_jTxtFldCups3FocusLost

    private void jTxtFldCups2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFldCups2FocusLost
        if(!"".equals(jTxtFldCups2.getText())) jTxtFldCups2.setText(Utilidades.rellenarCeros(jTxtFldCups2.getText(), 16));
    }//GEN-LAST:event_jTxtFldCups2FocusLost

    private void jTxtFldCups1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFldCups1FocusLost
        if(!"".equals(jTxtFldCups1.getText())) jTxtFldCups1.setText(Utilidades.rellenarCeros(jTxtFldCups1.getText(), 2));
    }//GEN-LAST:event_jTxtFldCups1FocusLost
    
    private void jCmbBxMunicipioInstItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxMunicipioInstItemStateChanged
        this.cambiarLocalidad(jCmbBxLocalidadInst, jCmbBxMunicipioInst, jCmbBxProvinciaInst);
        this.cambiarCP(jCmbBxMunicipioInst, jCmbBxProvinciaInst, jTxtFldCpInst);
    }//GEN-LAST:event_jCmbBxMunicipioInstItemStateChanged
    
    private void jCmbBxProvinciaInstItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxProvinciaInstItemStateChanged
        this.cambiarMunicipio(jCmbBxMunicipioInst, jCmbBxProvinciaInst);
    }//GEN-LAST:event_jCmbBxProvinciaInstItemStateChanged
    
    private void jBttnSelecTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSelecTecnicoActionPerformed
        FrmPrincipal frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
        DlgSeleccionarTecnico dlgSeleccionarTecnico = new DlgSeleccionarTecnico(frmPrincipal, true);
        dlgSeleccionarTecnico.setLocationRelativeTo(frmPrincipal);
        dlgSeleccionarTecnico.setVisible(true);
    }//GEN-LAST:event_jBttnSelecTecnicoActionPerformed
    
    private void jBtnDirCaractInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDirCaractInstActionPerformed
        Sesion.getInstance().setValorHt("provinciaCaractInst",jCmbBxProvinciaInst.getSelectedItem());
        Sesion.getInstance().setValorHt("municipioCaractInst",jCmbBxMunicipioInst.getSelectedItem());
        Sesion.getInstance().setValorHt("localidadCaractInst",jCmbBxLocalidadInst.getSelectedItem());
        FrmPrincipal frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
        DlgCallejeroCaractInst dlgCallejero = new DlgCallejeroCaractInst(frmPrincipal, true);
        dlgCallejero.setLocationRelativeTo(frmPrincipal);
        dlgCallejero.setVisible(true);
    }//GEN-LAST:event_jBtnDirCaractInstActionPerformed
    
    private void jBttnSelecInstaladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSelecInstaladorActionPerformed
        FrmPrincipal frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
        DlgEmpresaInst dlgEmpresaInst = new DlgEmpresaInst(frmPrincipal, true);
        dlgEmpresaInst.setLocationRelativeTo(frmPrincipal);
        dlgEmpresaInst.setVisible(true);
    }//GEN-LAST:event_jBttnSelecInstaladorActionPerformed

    private void jBtnDirTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDirTitularActionPerformed
        Sesion.getInstance().setValorHt("provinciaTitular",jCmbBxProvinciaTitular.getSelectedItem());
        Sesion.getInstance().setValorHt("municipioTitular",jCmbBxMunicipioTitular.getSelectedItem());
        Sesion.getInstance().setValorHt("localidadTitular",jCmbBxLocalidadTitular.getSelectedItem());
        FrmPrincipal frmPrincipal = (FrmPrincipal)Sesion.getInstance().getValorHt("objFrmPrincipal");
        DlgCallejeroTitular dlgCallejero = new DlgCallejeroTitular(frmPrincipal, true);
        dlgCallejero.setLocationRelativeTo(frmPrincipal);
        dlgCallejero.setVisible(true);
    }//GEN-LAST:event_jBtnDirTitularActionPerformed
    
    private void jCmbBxMunicipioTitularItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxMunicipioTitularItemStateChanged
        this.cambiarLocalidad(jCmbBxLocalidadTitular, jCmbBxMunicipioTitular, jCmbBxProvinciaTitular);
        this.cambiarCP(jCmbBxMunicipioTitular, jCmbBxProvinciaTitular, jTxtFldCpTitular);
    }//GEN-LAST:event_jCmbBxMunicipioTitularItemStateChanged
    
    private void jCmbBxProvinciaTitularItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbBxProvinciaTitularItemStateChanged
        this.cambiarMunicipio(jCmbBxMunicipioTitular, jCmbBxProvinciaTitular);
    }//GEN-LAST:event_jCmbBxProvinciaTitularItemStateChanged
    
    //Agrega a los Jcombox del formulario los datos tomados de la base de datos.
    private void agregarDatosCombox() {
        ResultSet rs = null;
        try{
            rs = bd.ejecSelect("SELECT * FROM PROVINCIAS ORDER BY PRNOM");
            jCmbBxProvinciaTitular.addItem(new ParCombo(0, ""));
            jCmbBxProvinciaInst.addItem(new ParCombo(0, ""));
            jCmbBxEmpSuministradora.addItem(new ParCombo(0,0,""));
            while(rs.next()){
                nomProv = rs.getString("PRNOM");
                codProv = rs.getInt("PRID");
                jCmbBxProvinciaTitular.addItem(new ParCombo(codProv, nomProv));
                jCmbBxProvinciaInst.addItem(new ParCombo(codProv, nomProv));
            }
            
            //Hay que agregar antes las modalidades de instalación antes que las categorías del instalador.
            rs = bd.ejecSelect("SELECT * FROM MODALIDAD_INST ORDER BY MIID");
            while(rs.next())
                jCmbBxModalidadEmp.addItem(new ParCombo(rs.getString(1), rs.getString(2)));
            rs = bd.ejecSelect("SELECT * FROM CAT_INSTALADOR ORDER BY CIDESC");
            while(rs.next())
                jCmbBxCatInst.addItem(new ParCombo(rs.getString(1), rs.getString(2)));
            
            //Carga de empresas suministradoras
            rs = bd.ejecSelect("SELECT * FROM EMP_SUMINISTRADORAS ORDER BY ESNOMBRE");
            while(rs.next())
                jCmbBxEmpSuministradora.addItem(new ParCombo(rs.getInt(1), rs.getInt(2),rs.getString(3)));
        } catch(SQLException e){
            Mensaje.error("FrmGestionPnl.java: "+e.getMessage(),e);
        }
        
        //Los comboboxes son autocompletables
        new AutoComplCmbBxRestrictivo(jCmbBxLocalidadTitular);
        new AutoComplCmbBxRestrictivo(jCmbBxLocalidadInst);
        new AutoComplCmbBxRestrictivo(jCmbBxMunicipioInst);
        new AutoComplCmbBxRestrictivo(jCmbBxMunicipioTitular);
        new AutoComplCmbBxRestrictivo(jCmbBxProvinciaTitular);
        new AutoComplCmbBxRestrictivo(jCmbBxProvinciaInst);
        new AutoComplCmbBxRestrictivo(jCmbBxCatInst);
        new AutoComplCmbBxRestrictivo(jCmbBxModalidadEmp);
        new AutoComplCmbBxRestrictivo(jCmbBxEmpSuministradora);
        
    }
    //Establece las restricciones del núm de caract que ha de tener cada campo
    public void establecerRestricciones() {
        // Se pone el limitador en al nº de caract deseados para la pestaña TITULAR y si son numéricos solo o no
        jTxtFldNombreTitular.setDocument(new LimitadorCaracteres(jTxtFldNombreTitular, 30, false, false));
        jTxtFldNifTitular.setDocument(new LimitadorCaracteres(jTxtFldNifTitular, 9, false, false));
        jTxtFldDomicilioTitular.setDocument(new LimitadorCaracteres(jTxtFldDomicilioTitular, 30, false, false));
        jTxtFldTelefonoTitular.setDocument(new LimitadorCaracteres(jTxtFldTelefonoTitular, 9, true, false));
        jTxtFldCpTitular.setDocument(new LimitadorCaracteres(jTxtFldCpTitular, 5, true, false));
        jTxtFldNifRepr.setDocument(new LimitadorCaracteres(jTxtFldNifRepr, 9, false, false));
        jTxtFldRepresentanteTitular.setDocument(new LimitadorCaracteres(jTxtFldRepresentanteTitular, 50, false, false));
        jTxtFldPortalTit.setDocument(new LimitadorCaracteres(jTxtFldPortalTit, 4, false, false));
        jTxtFldBisTit.setDocument(new LimitadorCaracteres(jTxtFldBisTit, 2, false, false));
        jTxtFldEscaleraTit.setDocument(new LimitadorCaracteres(jTxtFldEscaleraTit, 3, false, false));
        jTxtFldPisoTit.setDocument(new LimitadorCaracteres(jTxtFldPisoTit, 4, false, false));
        jTxtFldPuertaTit.setDocument(new LimitadorCaracteres(jTxtFldPuertaTit, 3, false, false));
        
        //Limitador de caracteres de EMPRESA SUMINISTRADORA
        //jTxtFldEmpSuministradora.setDocument(new LimitadorCaracteres(jTxtFldEmpSuministradora, 11, false, false));
        jTxtFldCups1.setDocument(new LimitadorCaracteres(jTxtFldCups1, 2, false, false));
        jTxtFldCups2.setDocument(new LimitadorCaracteres(jTxtFldCups2, 16, true, false));
        jTxtFldCups3.setDocument(new LimitadorCaracteres(jTxtFldCups3, 2, false, false));
        
        // Limitador de caract de la pestaña EMPRESA/INSTALADOR
        jTxtFldNombreEmpresa.setDocument(new LimitadorCaracteres(jTxtFldNombreEmpresa, 50, false, false));
        jTxtFldNumEmpresa.setDocument(new LimitadorCaracteres(jTxtFldNumEmpresa, 2, true, false));
        jTxtFldEibt.setDocument(new LimitadorCaracteres(jTxtFldEibt, 5, false, false));
        jTxtFldNombreInst.setDocument(new LimitadorCaracteres(jTxtFldNombreInst, 50, false, false));
        jTxtFldNumCarne.setDocument(new LimitadorCaracteres(jTxtFldNumCarne, 2, true, false));
        jTxtFldCcbt.setDocument(new LimitadorCaracteres(jTxtFldCcbt, 5, false, false));
        jTxtFldTelefonoEmp.setDocument(new LimitadorCaracteres(jTxtFldTelefonoEmp, 9, true, false));
        jTxtFldEmailEmp.setDocument(new LimitadorCaracteres(jTxtFldEmailEmp, 100, false, false));
        
        // Limitador de caract de la pestaña CARACTERISTICAS INSTALACION
        jTxtFldEmplazamientoInst.setDocument(new LimitadorCaracteres(jTxtFldEmplazamientoInst, 38, false, false));
        jTxtFldPortalInst.setDocument(new LimitadorCaracteres(jTxtFldPortalInst, 4, false, false));
        jTxtFldBisInst.setDocument(new LimitadorCaracteres(jTxtFldBisInst, 2, false, false));
        jTxtFldEscaleraInst.setDocument(new LimitadorCaracteres(jTxtFldEscaleraInst, 3, false, false));
        jTxtFldPisoInst.setDocument(new LimitadorCaracteres(jTxtFldPisoInst, 4, false, false));
        jTxtFldPuertaInst.setDocument(new LimitadorCaracteres(jTxtFldPuertaInst, 3, false, false));
        jTxtFldCpInst.setDocument(new LimitadorCaracteres(jTxtFldCpInst, 5, true, false));
        jTxtFldTelefonoInstalacion.setDocument(new LimitadorCaracteres(jTxtFldTelefonoInstalacion, 9, true, false));
        jTxtFldEmailInstalacion.setDocument(new LimitadorCaracteres(jTxtFldEmailInstalacion, 100, false, false));
        
        //Limitador de caract de la pestaña TÉCNICOC CUALIFICADO
        jTxtFldNombreTec.setDocument(new LimitadorCaracteres(jTxtFldNombreTec, 40,false, false));
        jTxtFldTituloTec.setDocument(new LimitadorCaracteres(jTxtFldTituloTec, 50,false, false));
        jTxtFldNumColegiado.setDocument(new LimitadorCaracteres(jTxtFldNumColegiado, 10,false, false));
        jTxtFldNIF.setDocument(new LimitadorCaracteres(jTxtFldNIF, 9,false, false));
        jTxtFldColegioOficial.setDocument(new LimitadorCaracteres(jTxtFldColegioOficial, 50,false, false));
    }
    
    private void cambiarMunicipio(JComboBox jCmbBxMunicipio, JComboBox jCmbBxProvincia){
        ResultSet rs = null;
        String consulta;
        jCmbBxMunicipio.removeAllItems();
        
        ParCombo combo = (ParCombo)jCmbBxProvincia.getSelectedItem();
        
        try{
            if(combo.getKeyInt() == 0)
                jCmbBxMunicipio.addItem(new ParCombo("0",""));
            else{
                consulta = "SELECT * FROM MUNICIPIOS WHERE MUPRID="+combo.getKeyInt()+" ORDER BY MUNOM";
                rs = bd.ejecSelect(consulta);
                while(rs.next())
                    jCmbBxMunicipio.addItem(new ParCombo(rs.getInt("MUID"),rs.getString("MUNOM")));
            }
        }
        catch(SQLException e){
            Mensaje.error("FrmGestionPnl.java: "+e.getMessage(),e);
        }      
    }
    

    private void cambiarLocalidad(JComboBox jCmbBxLocalidad, JComboBox jCmbBxMunicipio, JComboBox JCmbBxProvincia){
        ResultSet rs = null;
        String consulta;
        
        jCmbBxLocalidad.removeAllItems();
        
        if(jCmbBxMunicipio.getSelectedItem() != null){
            ParCombo parComboProvincia = (ParCombo)JCmbBxProvincia.getSelectedItem();
            ParCombo parComboMunicipio = (ParCombo)jCmbBxMunicipio.getSelectedItem();
            
            try{
                if(parComboProvincia.getKeyInt() == 0 || parComboProvincia.getKeyInt() == 0)
                    jCmbBxLocalidad.addItem(new ParCombo("0",""));
                else{
                    consulta = "SELECT * FROM LOCALIDADES WHERE LCPRID="+parComboProvincia.getKeyInt()+" AND LCMUID="+parComboMunicipio.getKeyInt()+" ORDER BY LCNOM";
                    rs = bd.ejecSelect(consulta);
                    while(rs.next())
                        jCmbBxLocalidad.addItem(new ParCombo(rs.getInt("LCID"),rs.getString("LCNOM")));
                }
                
            } catch(Exception e){
                Mensaje.error("FrmGestionPnl.java: "+e.getMessage(),e);
            }
        }
    }
    
    private void cambiarCP(JComboBox JCmbBxMunicipio, JComboBox JCmbBxProvincia, JTextField jTxtFldCp) {
        String consulta;
        
        if(JCmbBxMunicipio.getSelectedItem() != null){
            ParCombo parComboMunicipio = (ParCombo)JCmbBxMunicipio.getSelectedItem();
            ParCombo parComboProvincia = (ParCombo)JCmbBxProvincia.getSelectedItem();
            
            ResultSet rs = null;
            
            try{
                if(parComboProvincia.getKeyInt() == 0 || parComboMunicipio.getKeyInt() == 0)
                    jTxtFldCp.setText("");
                else{
                    consulta = "SELECT * FROM MUNICIPIOS WHERE MUPRID="+parComboProvincia.getKeyInt()+" AND MUID="+parComboMunicipio.getKeyInt();
                    rs = bd.ejecSelect(consulta);
                    rs.next();
                    jTxtFldCp.setText(rs.getString("MUCP"));
                }  
            }
            catch(Exception e){
                Mensaje.error("FrmGestionPnl.java: "+e.getMessage(),e);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDirCaractInst;
    private javax.swing.JButton jBtnDirTitular;
    private javax.swing.JButton jBttnSelecInstalador;
    private javax.swing.JButton jBttnSelecTecnico;
    public javax.swing.JComboBox jCmbBxCatInst;
    public javax.swing.JComboBox jCmbBxEmpSuministradora;
    public javax.swing.JComboBox jCmbBxLocalidadInst;
    public javax.swing.JComboBox jCmbBxLocalidadTitular;
    public javax.swing.JComboBox jCmbBxModalidadEmp;
    public javax.swing.JComboBox jCmbBxMunicipioInst;
    public javax.swing.JComboBox jCmbBxMunicipioTitular;
    public javax.swing.JComboBox jCmbBxProvinciaInst;
    public javax.swing.JComboBox jCmbBxProvinciaTitular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEmailInstalacion;
    private javax.swing.JLabel jLabelNIF;
    private javax.swing.JLabel jLabelTelefonoInstalacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPnlCaractInst;
    private javax.swing.JPanel jPnlEmpInst;
    private javax.swing.JPanel jPnlEmpSum;
    private javax.swing.JPanel jPnlTecnicoCualif;
    private javax.swing.JPanel jPnlTitular;
    public javax.swing.JTabbedPane jTbbdPnGestion;
    public javax.swing.JTextField jTxtFldBisInst;
    public javax.swing.JTextField jTxtFldBisTit;
    public javax.swing.JTextField jTxtFldCcbt;
    public javax.swing.JTextField jTxtFldColegioOficial;
    public javax.swing.JTextField jTxtFldCpInst;
    public javax.swing.JTextField jTxtFldCpTitular;
    public javax.swing.JTextField jTxtFldCups1;
    public javax.swing.JTextField jTxtFldCups2;
    public javax.swing.JTextField jTxtFldCups3;
    public javax.swing.JTextField jTxtFldDomicilioTitular;
    public javax.swing.JTextField jTxtFldEibt;
    public javax.swing.JTextField jTxtFldEmailEmp;
    public javax.swing.JTextField jTxtFldEmailInstalacion;
    public javax.swing.JTextField jTxtFldEmplazamientoInst;
    public javax.swing.JTextField jTxtFldEscaleraInst;
    public javax.swing.JTextField jTxtFldEscaleraTit;
    public javax.swing.JTextField jTxtFldNIF;
    public javax.swing.JTextField jTxtFldNIFInstalador;
    public javax.swing.JTextField jTxtFldNifRepr;
    public javax.swing.JTextField jTxtFldNifTitular;
    public javax.swing.JTextField jTxtFldNombreEmpresa;
    public javax.swing.JTextField jTxtFldNombreInst;
    public javax.swing.JTextField jTxtFldNombreTec;
    public javax.swing.JTextField jTxtFldNombreTitular;
    public javax.swing.JTextField jTxtFldNumCarne;
    public javax.swing.JTextField jTxtFldNumColegiado;
    public javax.swing.JTextField jTxtFldNumEmpresa;
    public javax.swing.JTextField jTxtFldPisoInst;
    public javax.swing.JTextField jTxtFldPisoTit;
    public javax.swing.JTextField jTxtFldPortalInst;
    public javax.swing.JTextField jTxtFldPortalTit;
    public javax.swing.JTextField jTxtFldPuertaInst;
    public javax.swing.JTextField jTxtFldPuertaTit;
    public javax.swing.JTextField jTxtFldRepresentanteTitular;
    public javax.swing.JTextField jTxtFldTelefonoEmp;
    public javax.swing.JTextField jTxtFldTelefonoInstalacion;
    public javax.swing.JTextField jTxtFldTelefonoTitular;
    public javax.swing.JTextField jTxtFldTituloTec;
    // End of variables declaration//GEN-END:variables
}
