/*
 * FrmPrincipal.java
 *
 * Created on 21 de julio de 2006, 10:36
 */

package forms;

import forms.establecer.SetInfoCaractGenerales;
import forms.establecer.SetInfoResumen;
import forms.recoger.ValidarDatos;
import funciones.Sesion;
import funciones.Utilidades;
import funciones.UtilidadesSQL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import main.Constantes;

/**
 *
 * @author  sanjose
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private FrmGraficoPnl frmGrafico = null;
    private FrmGestionPnl frmGestion = null;
    private FrmDatosTecnicosPnl frmDatosTecnicos = null;
    private FrmTramitarPnl frmTramitar = null;
    private ValidarDatos validar = null;
    private String txtErrorDatosGestion = "";
    private String txtErrorDatosTecnicos = "";
    private boolean esValidoDatosGestion, esValidoDatosTecn;
    private int pantallaActual;
    private int pantallaNueva;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        
            //Incluimos en la sesión esta clase.
            Sesion.getInstance().setValorHt("objFrmPrincipal", this);
            initComponents();

            frmGrafico = new FrmGraficoPnl();
            frmGestion = new FrmGestionPnl();
            frmDatosTecnicos = new FrmDatosTecnicosPnl();
            frmTramitar = new FrmTramitarPnl();
            
            validar = new ValidarDatos();
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane = new javax.swing.JSplitPane();
        jPnlLateral = new javax.swing.JPanel();
        jBtnDatosGestion = new javax.swing.JButton();
        jBtnDatosTecnicos = new javax.swing.JButton();
        jBtnGrafico = new javax.swing.JButton();
        jBtnMenuPrincipal = new javax.swing.JButton();
        jBtnTramitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/config/config"); // NOI18N
        setTitle(bundle.getString("TITULO")); // NOI18N
        setIconImage((new ImageIcon(getClass().getResource("/resources/icons/sibol.gif"))).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        getAccessibleContext().setAccessibleName(bundle.getString("TITULO")); // NOI18N
        jSplitPane.setDividerSize(0);
        jPnlLateral.setBackground(new java.awt.Color(255, 255, 255));
        jPnlLateral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnDatosGestion.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBtnDatosGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/frmgestion.png")));
        jBtnDatosGestion.setText("<html><center>Datos de<br>Gesti\u00f3n</center></html>");
        jBtnDatosGestion.setContentAreaFilled(false);
        jBtnDatosGestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnDatosGestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDatosGestion.setIconTextGap(0);
        jBtnDatosGestion.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnDatosGestion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDatosGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDatosGestionActionPerformed(evt);
            }
        });

        jBtnDatosTecnicos.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBtnDatosTecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/frmtecnicos.png")));
        jBtnDatosTecnicos.setText("<html><center>Datos<br>T\u00e9cnicos</center></html>");
        jBtnDatosTecnicos.setContentAreaFilled(false);
        jBtnDatosTecnicos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnDatosTecnicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDatosTecnicos.setIconTextGap(0);
        jBtnDatosTecnicos.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnDatosTecnicos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDatosTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDatosTecnicosActionPerformed(evt);
            }
        });

        jBtnGrafico.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBtnGrafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/frmgrafico.png")));
        jBtnGrafico.setText("<html><center>Esquema<br>Unifiliar</center></html>");
        jBtnGrafico.setContentAreaFilled(false);
        jBtnGrafico.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnGrafico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnGrafico.setIconTextGap(0);
        jBtnGrafico.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnGrafico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGraficoActionPerformed(evt);
            }
        });

        jBtnMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBtnMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/tofront.gif")));
        jBtnMenuPrincipal.setText("<html><center>Men\u00fa <br>Principal</center></html>");
        jBtnMenuPrincipal.setContentAreaFilled(false);
        jBtnMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnMenuPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnMenuPrincipal.setIconTextGap(0);
        jBtnMenuPrincipal.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnMenuPrincipal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenuPrincipalActionPerformed(evt);
            }
        });

        jBtnTramitar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBtnTramitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/tramitar.png")));
        jBtnTramitar.setText("<html><center>Tramitar<br>con<br>Industria</center></html>");
        jBtnTramitar.setContentAreaFilled(false);
        jBtnTramitar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnTramitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnTramitar.setIconTextGap(0);
        jBtnTramitar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jBtnTramitar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnTramitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTramitarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPnlLateralLayout = new org.jdesktop.layout.GroupLayout(jPnlLateral);
        jPnlLateral.setLayout(jPnlLateralLayout);
        jPnlLateralLayout.setHorizontalGroup(
            jPnlLateralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlLateralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPnlLateralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnMenuPrincipal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnGrafico, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnDatosGestion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnDatosTecnicos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jBtnTramitar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPnlLateralLayout.setVerticalGroup(
            jPnlLateralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlLateralLayout.createSequentialGroup()
                .addContainerGap()
                .add(jBtnGrafico)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnDatosGestion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnDatosTecnicos)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jBtnTramitar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 203, Short.MAX_VALUE)
                .add(jBtnMenuPrincipal)
                .addContainerGap())
        );
        jSplitPane.setLeftComponent(jPnlLateral);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaTramitar() {
        jSplitPane.setRightComponent(getFrmTramitar());
        pantallaActual = Constantes.PANTALLA_TRAMITAR;
    }
    
    private void pantallaEsquema() {
        jSplitPane.setRightComponent(getFrmGrafico());
        pantallaActual = Constantes.PANTALLA_ESQUEMA;
    }
    
    private void pantallaDatosTecnicos() {
        recargarFormularios();
        jSplitPane.setRightComponent(getFrmDatosTecnicos());
        pantallaActual = Constantes.PANTALLA_DATOS_TECNICOS;
    }
    
    private void pantallaDatosGestion() {
        recargarFormularios();
        jSplitPane.setRightComponent(getFrmGestion());
        pantallaActual = Constantes.PANTALLA_DATOS_GESTION;
    }
    
    private void jBtnTramitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTramitarActionPerformed
        if(pantallaActual == Constantes.PANTALLA_TRAMITAR) return;
        pantallaNueva = Constantes.PANTALLA_TRAMITAR;
        if(validaciones()) pantallaTramitar();
    }//GEN-LAST:event_jBtnTramitarActionPerformed

    private void jBtnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenuPrincipalActionPerformed
        if(validaciones()) {
            JOptionPane optionPane=new JOptionPane();
            //Object[] opciones={"Aceptar","Cancelar"};
            //int ret=optionPane.showOptionDialog(null,"¿CONFIRMA QUE DESEA SALIR AL MENÚ PRINCIPAL?\n          Los datos no guardados se perderán ","SIBOL",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
            //if(ret==JOptionPane.YES_OPTION) {
                this.setVisible(false);
                JFrame frm = Sesion.getInstance().getFrmEntrada();
                Utilidades.igualarFormularios(frm, this);
                frm.setVisible(true);
                // resetea los datos de la sesión.
                Sesion.getInstance().reset();
            //}
        }
    }//GEN-LAST:event_jBtnMenuPrincipalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pantallaEsquema();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane optionPane=new JOptionPane();
	Object[] opciones={"Aceptar","Cancelar"};
	int ret=optionPane.showOptionDialog(null,"¿CONFIRMA QUE DESEA SALIR DE LA APLICACIÓN?\n          Los datos no guardados se perderán ","SIBOL",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
        if(ret==JOptionPane.YES_OPTION) Sesion.getInstance().cerrarAplicacion();
    }//GEN-LAST:event_formWindowClosing

    private void jBtnDatosTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDatosTecnicosActionPerformed
        if(pantallaActual == Constantes.PANTALLA_DATOS_TECNICOS) return;
        pantallaNueva = Constantes.PANTALLA_DATOS_TECNICOS;
        if(validaciones()) pantallaDatosTecnicos();
    }//GEN-LAST:event_jBtnDatosTecnicosActionPerformed

    private void jBtnDatosGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDatosGestionActionPerformed
        if(pantallaActual == Constantes.PANTALLA_DATOS_GESTION) return;
        pantallaNueva = Constantes.PANTALLA_DATOS_GESTION;
        if(validaciones()) pantallaDatosGestion();
    }//GEN-LAST:event_jBtnDatosGestionActionPerformed

    private void jBtnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGraficoActionPerformed
        if(pantallaActual == Constantes.PANTALLA_ESQUEMA) return;
        pantallaNueva = Constantes.PANTALLA_ESQUEMA;
        if(validaciones()) pantallaEsquema();
    }//GEN-LAST:event_jBtnGraficoActionPerformed

    public FrmGraficoPnl getFrmGrafico() {
        return frmGrafico;
    }

    public FrmGestionPnl getFrmGestion() {
        return frmGestion;
    }

    public FrmDatosTecnicosPnl getFrmDatosTecnicos() {
        return frmDatosTecnicos;
    }
    
    public FrmTramitarPnl getFrmTramitar() {
        return frmTramitar;
    }
    
    public void recargarFormularios(){
        int idInstalacion =((Integer)Sesion.getInstance().getValorHt(Constantes.SES_INSTALACIONES_ID)).intValue();
        SetInfoCaractGenerales setInfoCaractGenerales = new SetInfoCaractGenerales(this,idInstalacion);
        setInfoCaractGenerales.getInfoBD();
        setInfoCaractGenerales.rellenarFormulario();
        SetInfoResumen setInfoResumen = new SetInfoResumen(this,idInstalacion);
        setInfoResumen.getInfoBD();
        setInfoResumen.rellenarFormulario();
    }
    
    public void cargarXML(){
        frmGrafico.cargarXML();
    }

    private boolean validaciones() {
        String mensajeError = null;
        String mensajeWarning = null;
        
        // validación de datos de gestión
        if(pantallaActual == Constantes.PANTALLA_DATOS_GESTION) {
            validar.procesarDatosGestionPnl();
            if(!validar.esValidoDatosGestion()) {
                mensajeError = "Se han producido errores en el apartado DATOS DE GESTION:\n"+validar.getTxtErrorDatosGestion();
            }
        }
        
        // validación de datos técnicos
        if(pantallaActual == Constantes.PANTALLA_DATOS_TECNICOS) {
            validar.procesarDatosTecnicosPnl();
            if(!validar.esValidoDatosTecnicos()) {
                mensajeError = "Se han producido errores en el apartado DATOS TECNICOS:\n"+validar.getTxtErrorDatosTecnicos();
            }
        }
        
        // validación del esquema
        boolean vivienda = UtilidadesSQL.esVivienda();
        boolean reforma = UtilidadesSQL.esReforma();
        if(pantallaActual == Constantes.PANTALLA_ESQUEMA) {
            String[] mensajes = frmGrafico.guardarDatosBD(vivienda, reforma);
            if(mensajes!=null) {
                if(mensajes[0]!=null) {
                    mensajeError = "Se han producido errores en el apartado ESQUEMA UNIFILIAR:\n"+mensajes[0];
                } else if(mensajes[1]!=null) {
                    mensajeWarning = "Aviso en el apartado ESQUEMA UNIFILIAR:\n"+mensajes[1];
                }
            }
        }
        
        if(mensajeError != null) {
            JOptionPane optionPane=new JOptionPane();
            Object[] opciones={"Si", "No"};
            int ret=optionPane.showOptionDialog(null,mensajeError + "\n¿Desea continuar?","SIBOL",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
            if(ret != JOptionPane.YES_OPTION) return false;
        }
        if(mensajeWarning != null) {
            JOptionPane optionPane=new JOptionPane();
            Object[] opciones={"Si", "No"};
            int ret=optionPane.showOptionDialog(null,mensajeWarning + "\n¿Desea continuar?","SIBOL",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
            if(ret != JOptionPane.YES_OPTION) return false;
        }
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDatosGestion;
    private javax.swing.JButton jBtnDatosTecnicos;
    private javax.swing.JButton jBtnGrafico;
    private javax.swing.JButton jBtnMenuPrincipal;
    private javax.swing.JButton jBtnTramitar;
    private javax.swing.JPanel jPnlLateral;
    private javax.swing.JSplitPane jSplitPane;
    // End of variables declaration//GEN-END:variables
}
